### ISSUE TITLE
ReferenceError: parsed is not defined

### ISSUE THREAD

**Issue by raylas** [boscoh/embellish#3]
Hello,

I'm on **MacOS 10.12.5**, **Node v8.1.2**, **npm v5.0.3**.

---

After installing embellish, every attempt at running it resulted in:
```

/usr/local/lib/node_modules/embellishjs/embellish.js:354
  parsed = parseOptions();
         ^

ReferenceError: parsed is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/embellishjs/embellish.js:354:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

```

Runs without issue after adding a `let` statement on `line 354` of **embellish.js** at the path in the error above:

```
...
if (require.main === module) {

  let parsed = parseOptions(); // LINE 354

  let site = {
    url: '', // if '' then use relative urls
    outputDir: '.',  // generated files and static files put here
...
```

Thanks for a great tool.

**Comment by boscoh** [comment]
Thanks for reporting this. I think that bug has been fixed in the meantime. Much appreciated.
